[package]
name = "chess-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossbeam = "0.8.4"
crossterm = "0.27.0"
futures = "0.3.30"
ratatui = "0.27.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
